# Bibliography

Cardona, Carolina, Jean Christophe Rusatira, Xiaomeng Cheng, Claire Silberg, Ian Salas, Qingfeng Li, David Bishai, and Jose G. Rimon. "Generating and Capitalizing on the Demographic Dividend Potential in Sub-Saharan Africa: A Conceptual Framework from a Systematic Literature Review." *Gates Open Research* 4 (2020).

Chutel, Lynsey, and Gulshan Khan. "One Year in the Infuriating and Humiliating Search for a Job in South Africa." *The New York Times* (Digital Edition), 2023.

Doepke, Matthias, Anne Hannusch, Fabian Kindermann, and Michèle Tertilt. "New Economics of Fertility." IMF, 2022. Accessed May 22, 2024. [https://www.imf.org/en/Publications/fandd/issues/Series/Analytical-Series/new-economics-of-fertility-doepke-hannusch-kindermann-tertilt](https://www.imf.org/en/Publications/fandd/issues/Series/Analytical-Series/new-economics-of-fertility-doepke-hannusch-kindermann-tertilt).

Duarte, Cristina. “Sustainable Financing for (an Owned) Sustainable Development: Time for Africa to Give the Driver’s Seat to Domestic Resource Mobilization.” In *Recovering Better: Economic and Social Challenges and Opportunities*, United Nations, Department of Economic and Social Affairs, 2020.

IMF. "Chart of the Week: Bye Bye Baby—How Crises Affect Fertility Rates." *IMF*. Accessed May 22, 2024. [https://www.imf.org/en/Blogs/Articles/2018/11/13/chart-of-the-week-bye-bye-baby-how-crises-affect-fertility-rates](https://www.imf.org/en/Blogs/Articles/2018/11/13/chart-of-the-week-bye-bye-baby-how-crises-affect-fertility-rates).

———. "Regional Economic Outlook." 2024.

———. "Sub-Saharan Africa's Growth Requires Quality Education for Growing Population." *IMF*. Accessed May 22, 2024. [https://www.imf.org/en/Blogs/Articles/2024/04/25/sub-saharan-africas-growth-requires-quality-education-for-growing-population](https://www.imf.org/en/Blogs/Articles/2024/04/25/sub-saharan-africas-growth-requires-quality-education-for-growing-population).

International Labour Organization (ILO). "Making Labour Statistics Work for Women: Recent Developments and the Way Ahead." ILOSTAT, 2024. Accessed May 22, 2024. [https://ilostat.ilo.org/blog/making-labour-statistics-work-for-women-recent-developments-and-the-way-ahead/](https://ilostat.ilo.org/blog/making-labour-statistics-work-for-women-recent-developments-and-the-way-ahead/).

———. "Women Are More Likely Than Men to Want a Job But Not Have One." ILOSTAT, 2024. Accessed May 22, 2024. [https://ilostat.ilo.org/blog/women-are-more-likely-than-men-to-want-a-job-but-not-have-one/](https://ilostat.ilo.org/blog/women-are-more-likely-than-men-to-want-a-job-but-not-have-one/).

———. "Women with Young Children Have Much Lower Labour Force Participation Rates." ILOSTAT, 2024. Accessed May 22, 2024. [https://ilostat.ilo.org/blog/women-with-young-children-have-much-lower-labour-force-participation-rates/](https://ilostat.ilo.org/blog/women-with-young-children-have-much-lower-labour-force-participation-rates/).

Our World in Data. "Population Growth." *Our World in Data*. Accessed May 22, 2024. [https://ourworldindata.org/population-growth?insight=the-un-expects-the-global-population-to-peak-by-the-end-of-the-century#key-insights](https://ourworldindata.org/population-growth?insight=the-un-expects-the-global-population-to-peak-by-the-end-of-the-century#key-insights).

———. "Population Momentum: If the Number of Children per Woman Is Falling, Why Is the Population Still Increasing?" *Our World in Data*. Accessed May 22, 2024. [https://ourworldindata.org/population-momentum](https://ourworldindata.org/population-momentum).

———. "Access to Basic Education: Almost 60 Million Children of Primary School Age Are Not in School." *Our World in Data*. Accessed May 22, 2024. [https://ourworldindata.org/children-not-in-school#:~:text=This%20means%20that%2C%20in%20total,and%20conflict%2Daffected%20areas%E2%80%9D.](https://ourworldindata.org/children-not-in-school#:~:text=This%20means%20that%2C%20in%20total,and%20conflict%2Daffected%20areas%E2%80%9D.).

———. "Demographic Transition: Why Is Rapid Population Growth a Temporary Phenomenon?" *Our World in Data*. Accessed May 22, 2024. [https://ourworldindata.org/demographic-transition](https://ourworldindata.org/demographic-transition).

———. "The Global Population Pyramid: How Global Demography Has Changed and What We Can Expect for the 21st Century." *Our World in Data*. Accessed May 22, 2024. [https://ourworldindata.org/global-population-pyramid](https://ourworldindata.org/global-population-pyramid).

———. "Ensure Inclusive and Quality Education for All and Promote Lifelong Learning." *Our World in Data*. Accessed May 22, 2024. [https://ourworldindata.org/sdgs/quality-education](https://ourworldindata.org/sdgs/quality-education).

Sauda, Mukhtar, and Emmanuel Pinto Moreira. "GROUPE DE LA BANQUE AFRICAINE DE DÉVELOPPEMENT." 2020.

United Nations Department of Economic and Social Affairs (UN-DESA). "Selecting Adolescent Birth Rates (10-14 and 15-19 Years) for Monitoring and Reporting on Sustainable Development Goals." *United Nations*. Accessed May 22, 2024. [https://www.un.org/development/desa/pd/sites/www.un.org.development.desa.pd/files/undesa_pd_2022_tp_selecting-abr-data-for-sdg-reporting.pdf](https://www.un.org/development/desa/pd/sites/www.un.org.development.desa.pd/files/undesa_pd_2022_tp_selecting-abr-data-for-sdg-reporting.pdf).

———. "Population, Education and Sustainable Development: Interlinkages and Select Policy Implications." *United Nations*. Accessed May 22, 2024. [https://www.un.org/development/desa/pd/sites/www.un.org.development.desa.pd/files/undesa_pd_2023_cpd56_policy-brief-152.pdf](https://www.un.org/development.desa/pd/sites/www.un.org.development.desa.pd/files/undesa_pd_2023_cpd56_policy-brief-152.pdf).

———. "Global Population Growth and Sustainable Development." February 2022. *United Nations*. Accessed May 22, 2024. [https://www.un.org/development/desa/pd/sites/www.un.org.development.desa.pd/files/undesa_pd_2022_key_messages_global_population_growth.pdf](https://www.un.org/development.desa/pd/sites/www.un.org.development.desa.pd/files/undesa_pd_2022_key_messages_global_population_growth.pdf).

———. "World Population Prospects 2019: Highlights." *United Nations*. Accessed May 22, 2024. [https://population.un.org/wpp/Publications/Files/WPP2019_10KeyFindings.pdf](https://population.un.org/wpp/Publications/Files/WPP2019_10KeyFindings.pdf).

United Nations Educational, Scientific and Cultural Organization. "Education Finance Watch 2023." *United Nations Educational, Scientific and Cultural Organization*. Accessed May 22, 2024. [https://unesdoc.unesco.org/ark:/48223/pf0000387042](https://unesdoc.unesco.org/ark:/48223/pf0000387042).

"Adolescent Pregnancy Factsheet." *World Health Organization*. Accessed May 22, 2024. [https://www.who.int/news-room/fact-sheets/detail/adolescent-pregnancy](https://www.who.int/news-room/fact-sheets/detail/adolescent-pregnancy).

"The World Is Becoming More African." *The New York Times*. Accessed May 22, 2024. [https://www.nytimes.com/interactive/2023/10/28/world/africa/africa-youth-population.html](https://www.nytimes.com/interactive/2023/10/28/world/africa/africa-youth-population.html).